DELIMITER //

CREATE TRIGGER verify_isbn 
BEFORE INSERT ON books
FOR EACH ROW
BEGIN
IF LENGTH(NEW.isbn) != 13 THEN 
SIGNAL SQLSTATE "10000"
SET MESSAGE_TEXT = "ERROR: ISBN MUST BE 13 DIGITS";
END IF;
END//

DELIMITER ;